# Generated by Django 4.2.3 on 2023-07-10 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название ингредиента.')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('measure_units', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название Тега.')),
                ('color_code', models.CharField(max_length=7, unique=True, verbose_name='HEX-код цвета.')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Слаг.')),
            ],
            options={
                'verbose_name': ('Тег.',),
                'verbose_name_plural': 'Теги.',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название рецепта.')),
                ('image', models.ImageField(blank=True, upload_to='recipes/', verbose_name='Фото рецепта.')),
                ('text', models.TextField(verbose_name='Подробное описание рецепта.')),
                ('cooking_time', models.PositiveBigIntegerField(verbose_name='Время приготовления.')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации.')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта.')),
                ('ingredients', models.ManyToManyField(to='recipes.ingredient', verbose_name='Название ингредиента.')),
                ('tag', models.ManyToManyField(to='recipes.tag', verbose_name='Название тега.')),
            ],
            options={
                'verbose_name': ('Рецепт',),
                'verbose_name_plural': ('Рецепты',),
                'ordering': ('-created',),
            },
        ),
    ]
