# Generated by Django 4.2.3 on 2023-07-17 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
