# Generated by Django 4.2.3 on 2023-07-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_rename_quantity_ingredient_amount_alter_recipe_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientToLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название ингредиента.')),
                ('measurement_unit', models.CharField(max_length=50, verbose_name='Единица измерения.')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
    ]
