# Generated by Django 4.2.3 on 2023-07-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_ingredienttoload'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredienttoload',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Количество ингредиента.'),
        ),
    ]
