# Generated by Django 4.2.3 on 2023-07-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_ingredienttoload_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IngredientToLoad',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Количество ингредиента.'),
        ),
    ]
