# Generated by Django 4.2.3 on 2023-07-28 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_rename_ingredients_recipe_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_ingredients',
            new_name='ingredients',
        ),
    ]
