# Generated by Django 4.2.3 on 2023-07-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_rename_recipe_ingredients_recipe_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='measurement_unit',
        ),
    ]
